"""empty message

Revision ID: 920ec4a491f5
Revises: 0d05f5e6c93b
Create Date: 2026-07-08 10:56:06.255955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '920ec4a491f5'
down_revision = '0d05f5e6c93b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fav__vehiculos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehiculos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('tamaño', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehiculos')
    op.drop_table('fav__vehiculos')
    # ### end Alembic commands ###
